# Generated by Django 2.2.2 on 2022-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_place_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='SorlPhoto/%Y', verbose_name='IMAGE'),
        ),
    ]
